#调试模式
debug: false
#配置文件
#击杀提示
KillTip: "%prefix% &a你击杀怪物%mob%,获得了&e%money%&a杀币,今日上限%nowkill%-%maxkill%"
LimitTip: "%prefix% &c你已达到击杀上限&e%limit%&c,无法获得更多杀币"
#信息提示开关
MessageTip:
  #聊天栏提示
  Chat: true
  #ActionBar提示
  ActionBar: true
  #Title
  Title: true
#Title参数配置
TitleConfig:
  #Tick为单位 1秒=20Tick
  #淡入时间
  fadeIn: 20
  #显示时间
  stay: 70
  #淡出时间
  fadeOut: 20

#定时器配置
#多少秒检测一次时间
timeCheck: 60
#权限限制
permLimit:
  #默认每日击杀配置
  #完整结构为mountainkill.default 以此类推
  mountainkill:
    #默认权限(不可删除)
    default:
      #优先级
      priority: 1
      #击杀上限
      kill: 100
      #奖励配置
      money:
        #此处一定要填大写 否则不识别
        #两种写法都可以
        #第一种写法
        ZOMBIE:
          min: 20
          max: 100
        #第二种写法 30为最低 100为最高
        SKELETON: [30,100]
    #自定义后缀 完整结构为mountainkill.vip1 以此类推
    vip1:
      #优先级(当玩家拥有多个权限时 则应用优先级最高的权限配置)
      priority: 2
      #击杀上限
      kill: 200
      #奖励配置
      money:
        #ALL则为所有怪物
        ALL:
          min: 500
          max: 1000